import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const hsbcFont = localFont({
  src: "./fonts/UniversNext.woff",
  variable: "--font-hsbc-font",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body
        className={`${hsbcFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
